"""create bioJobModel

Revision ID: ff04192460e2
Revises: 
Create Date: 2026-01-12 23:00:09.985618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff04192460e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_generation_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bio_generation_jobs_id'), 'bio_generation_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bio_generation_jobs_id'), table_name='bio_generation_jobs')
    op.drop_table('bio_generation_jobs')
    # ### end Alembic commands ###
